In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings("ignore")  # 忽略警告

plt.rcParams['font.sans-serif'] = ['SimHei']  # 中文字体设置-黑体
plt.rcParams['axes.unicode_minus'] = False  # 解决保存图像是负号'-'显示为方块的问题
sns.set(font='SimHei')  # 解决Seaborn中文显示问题

In [2]:
data = pd.read_excel(r'C:\Users\dell\Desktop\CD_Dividend.xlsx',sheet_name='A股')
data2 = data[data['预案内容']!='不分配不转增']

In [3]:
data.head()

,证券代码,证券简称,行业代码,二级行业名称,一级行业名称,财政年度,预案公告日期,预案内容,方案实施进度,实施方案公告日期,...,转增比,派息比税前,送转数量(股),派息数(元),股权登记日,最后交易日,除权除息日,派息日,股权登记日收盘价(元),除权除息日收盘价(元)
0,1,深发展A,J66,货币金融服务,金融业,2010,2010-08-25,不分配不转增,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,深发展A,J66,货币金融服务,金融业,2010,2011-02-25,不分配不转增,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,深发展A,J66,货币金融服务,金融业,2011,2011-08-18,不分配不转增,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,深发展A,J66,货币金融服务,金融业,2011,2012-03-09,不分配不转增,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,ST 国农,I65,软件和信息技术服务业,信息传输、计算机服务和软件业,2010,2010-08-20,不分配不转增,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49549 entries, 0 to 49548
Data columns (total 22 columns):
证券代码           49549 non-null int64
证券简称           49549 non-null object
行业代码           49549 non-null object
二级行业名称         49549 non-null object
一级行业名称         49549 non-null object
财政年度           49549 non-null int64
预案公告日期         49549 non-null object
预案内容           49549 non-null object
方案实施进度         49549 non-null int64
实施方案公告日期       19574 non-null object
实施方案内容         19574 non-null object
送股比            698 non-null float64
转增比            4883 non-null float64
派息比税前          18945 non-null float64
送转数量(股)        5117 non-null float64
派息数(元)         18811 non-null float64
股权登记日          19574 non-null object
最后交易日          0 non-null float64
除权除息日          19563 non-null object
派息日            18811 non-null object
股权登记日收盘价(元)    18542 non-null float64
除权除息日收盘价(元)    18546 non-null float64
dtypes: float64(8), int64(3), object(11)
memory usage: 8.3+ MB

In [5]:
data2.head()

,证券代码,证券简称,行业代码,二级行业名称,一级行业名称,财政年度,预案公告日期,预案内容,方案实施进度,实施方案公告日期,...,转增比,派息比税前,送转数量(股),派息数(元),股权登记日,最后交易日,除权除息日,派息日,股权登记日收盘价(元),除权除息日收盘价(元)
11,2,万科A,K70,房地产业,房地产业,2010,2011-03-08,10派1元(含税),3,2011-05-20,...,NaN,0.100,NaN,1.099521e+09,2011-05-26,NaN,2011-05-27,2011-05-27,7.90,7.90
13,2,万科A,K70,房地产业,房地产业,2011,2012-03-13,10股派1.3元(含税),3,2012-06-27,...,NaN,0.130,NaN,1.429377e+09,2012-07-04,NaN,2012-07-05,2012-07-05,9.11,9.29
15,6,深振业A,K70,房地产业,房地产业,2010,2011-03-31,10送3股派0.6元(含税),3,2011-06-08,...,NaN,0.060,228232467.9,4.564649e+07,2011-06-13,NaN,2011-06-14,2011-06-14,7.18,5.56
32,9,中国宝安,S90,综合,综合,2010,2011-03-23,10派0.2元(含税),3,2011-07-27,...,NaN,0.020,NaN,2.181501e+07,2011-08-02,NaN,2011-08-03,2011-08-03,20.54,20.15
35,14,沙河股份,K70,房地产业,房地产业,2010,2011-04-25,10派0.35元(含税),3,2011-07-12,...,NaN,0.035,NaN,7.059682e+06,2011-07-15,NaN,2011-07-18,2011-07-18,8.15,8.18

In [6]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19743 entries, 11 to 49548
Data columns (total 22 columns):
证券代码           19743 non-null int64
证券简称           19743 non-null object
行业代码           19743 non-null object
二级行业名称         19743 non-null object
一级行业名称         19743 non-null object
财政年度           19743 non-null int64
预案公告日期         19743 non-null object
预案内容           19743 non-null object
方案实施进度         19743 non-null int64
实施方案公告日期       19574 non-null object
实施方案内容         19574 non-null object
送股比            698 non-null float64
转增比            4882 non-null float64
派息比税前          18942 non-null float64
送转数量(股)        5117 non-null float64
派息数(元)         18811 non-null float64
股权登记日          19574 non-null object
最后交易日          0 non-null float64
除权除息日          19563 non-null object
派息日            18811 non-null object
股权登记日收盘价(元)    18542 non-null float64
除权除息日收盘价(元)    18546 non-null float64
dtypes: float64(8), int64(3), object(11)
memory usage: 3.5+ MB

In [7]:
data['一级行业名称'].unique()

array(['金融业', '信息传输、计算机服务和软件业', '水利、环境和公共设施管理业', '房地产业', '建筑业', '制造业',
       '综合', '批发和零售业', '交通运输、仓储和邮政业', '电力、热力、燃气及水生产和供应业', '住宿和餐饮业',
       '租赁和商务服务业', '采矿业', '科学研究和技术服务业', '文化、体育和娱乐业', '卫生和社会工作', '教育',
       '农、林、牧、渔业', '居民服务、修理和其他服务业'], dtype=object)

In [8]:
len(data['一级行业名称'].unique())

19

共19个行业<br>
分别为('金融业', '信息传输、计算机服务和软件业', '水利、环境和公共设施管理业', '房地产业', '建筑业', '制造业','综合',<br>
       '批发和零售业', '交通运输、仓储和邮政业','电力、热力、燃气及水生产和供应业', '住宿和餐饮业','租赁和商务服务业',<br>
       '采矿业', '科学研究和技术服务业', '文化、体育和娱乐业', '卫生和社会工作', '教育','农、林、牧、渔业',<br>
       '居民服务、修理和其他服务业'）

# 股利分配率分析

分析2010-2018年各行业的总体股利分配率<br>
分析2010-2018年各行业的公司股利分配率<br>
分析2010-2018年历年各行业的总体股利分配率<br>

## 股利分配总次数的行业分布情况

In [9]:
data2['一级行业名称'].value_counts()

制造业                 12076
信息传输、计算机服务和软件业       1515
批发和零售业                952
房地产业                  789
交通运输、仓储和邮政业           698
电力、热力、燃气及水生产和供应业      624
金融业                   614
建筑业                   540
采矿业                   435
文化、体育和娱乐业             305
租赁和商务服务业              278
水利、环境和公共设施管理业         277
科学研究和技术服务业            201
农、林、牧、渔业              194
综合                     96
卫生和社会工作                61
住宿和餐饮业                 49
教育                     37
居民服务、修理和其他服务业           2
Name: 一级行业名称, dtype: int64

## 上市公司总数量、分配股利公司总数分析

In [10]:
#公司去重数量统计
def count(a,b):
    num = a.drop_duplicates('证券简称').shape[0]
    num2 = b.drop_duplicates('证券简称').shape[0]
    alist = [num,num2]
    return alist

2010-2018总上市公司数与分配股利公司数

In [11]:
num = count(data,data2)
num

[4911, 3989]

2010-2018历年上市公司数与分配股利公司数

In [12]:
data2010=data[data['财政年度']==2010]
data2011=data[data['财政年度']==2011]
data2012=data[data['财政年度']==2012]
data2013=data[data['财政年度']==2013]
data2014=data[data['财政年度']==2014]
data2015=data[data['财政年度']==2015]
data2016=data[data['财政年度']==2016]
data2017=data[data['财政年度']==2017]
data2018=data[data['财政年度']==2018]

data10= data2[data2['财政年度']==2010]
data11= data2[data2['财政年度']==2011]
data12= data2[data2['财政年度']==2012]
data13= data2[data2['财政年度']==2013]
data14= data2[data2['财政年度']==2014]
data15= data2[data2['财政年度']==2015]
data16= data2[data2['财政年度']==2016]
data17= data2[data2['财政年度']==2017]
data18= data2[data2['财政年度']==2018]

In [13]:
alist = [count(data2010,data10)[0],count(data2011,data11)[0],count(data2010,data12)[0],
         count(data2013,data13)[0],count(data2014,data14)[0],count(data2015,data15)[0],
         count(data2016,data16)[0],count(data2017,data17)[0],count(data2018,data18)[0],count(data,data2)[0]]
blist = [count(data2010,data10)[1],count(data2011,data11)[1],count(data2010,data12)[1],
         count(data2013,data13)[1],count(data2014,data14)[1],count(data2015,data15)[1],
         count(data2016,data16)[1],count(data2017,data17)[1],count(data2018,data18)[1],count(data,data2)[1]]
blist

[1393, 1666, 1844, 1917, 2008, 2092, 2460, 2810, 2635, 3989]

In [14]:
c = {'总上市公司数':alist,'发生股利分配公司数':blist}
df = pd.DataFrame(c,index = [2010,2011,2012,2013,2014,2015,2016,2017,2018,'合计'])
df['占比'] = df['发生股利分配公司数'][0:9]/df['总上市公司数'][0:9]
df.loc['合计','占比'] = df.loc['合计','发生股利分配公司数']/df.loc['合计','总上市公司数']
df

      总上市公司数  发生股利分配公司数        占比
2010    2147       1393  0.648812
2011    2426       1666  0.686727
2012    2147       1844  0.858873
2013    2573       1917  0.745045
2014    2739       2008  0.733114
2015    2927       2092  0.714725
2016    3240       2460  0.759259
2017    3567       2810  0.787777
2018    3678       2635  0.716422
合计      4911       3989  0.812258

## 各行业发生股利分配公司占比

In [15]:
#公司去重统计行业分布
def qvchongtongji(data):
    company = data.drop_duplicates(['证券简称'])
    coindustries_series = company['一级行业名称'].value_counts()
    return coindustries_series

def gulizhanbi(a,b):
    c = qvchongtongji(a)
    d = qvchongtongji(b)
    df = pd.concat([c,d, d/c],join='outer', axis=1)
    df.columns = ['上市公司行业分布数目','有股利分配的上市公司行业数目','占比']
    df = df.sort_values(by = '占比',ascending=False)
    return df

In [16]:
gulizhanbi(data,data2)

                  上市公司行业分布数目  有股利分配的上市公司行业数目        占比
居民服务、修理和其他服务业              2               2  1.000000
金融业                      135             121  0.896296
水利、环境和公共设施管理业             75              65  0.866667
交通运输、仓储和邮政业              131             111  0.847328
制造业                     2926            2441  0.834245
建筑业                      131             107  0.816794
信息传输、计算机服务和软件业           397             322  0.811083
科学研究和技术服务业                68              55  0.808824
批发和零售业                   242             189  0.780992
房地产业                     185             143  0.772973
租赁和商务服务业                  79              61  0.772152
卫生和社会工作                   23              17  0.739130
文化、体育和娱乐业                 93              68  0.731183
电力、热力、燃气及水生产和供应业         162             116  0.716049
农、林、牧、渔业                  60              42  0.700000
采矿业                      124              85  0.685484
住宿和餐饮业                    17              11  0.647059
教育                        17              11  0.647059
综合                        44              22  0.500000

In [17]:
df = pd.concat([pd.DataFrame(gulizhanbi(data2010,data10)['占比']),pd.DataFrame(gulizhanbi(data2011,data11)['占比']),
               pd.DataFrame(gulizhanbi(data2012,data12)['占比']),pd.DataFrame(gulizhanbi(data2013,data13)['占比']),
               pd.DataFrame(gulizhanbi(data2014,data14)['占比']),pd.DataFrame(gulizhanbi(data2015,data15)['占比']),
               pd.DataFrame(gulizhanbi(data2016,data16)['占比']),pd.DataFrame(gulizhanbi(data2017,data17)['占比']),
               pd.DataFrame(gulizhanbi(data2018,data18)['占比'])]
               ,axis = 1)
df.columns = [i for i in range(2010,2019)]
df = df.fillna(0)
df['平均分配率'] = df.mean(1)
df.sort_values(by='平均分配率',ascending = False)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,平均分配率
交通运输、仓储和邮政业,0.812500,0.837500,0.833333,0.811765,0.860465,0.840909,0.820000,0.888889,0.831776,0.837460
金融业,0.629032,0.701493,0.821918,0.797101,0.763158,0.805195,0.852273,0.891304,0.875000,0.792942
建筑业,0.763636,0.703125,0.750000,0.753623,0.750000,0.810811,0.816092,0.836957,0.793478,0.775302
信息传输、计算机服务和软件业,0.619403,0.715152,0.774725,0.814815,0.753695,0.770642,0.826255,0.779783,0.675000,0.747719
制造业,0.681518,0.715096,0.737340,0.754805,0.752761,0.727013,0.756990,0.796305,0.723627,0.738384
水利、环境和公共设施管理业,0.517241,0.617647,0.794118,0.705882,0.756098,0.697674,0.840909,0.792453,0.769231,0.721250
文化、体育和娱乐业,0.515152,0.628571,0.589744,0.675676,0.682927,0.755556,0.826923,0.883333,0.644068,0.689105
科学研究和技术服务业,0.625000,0.555556,0.666667,0.578947,0.629630,0.709677,0.710526,0.833333,0.807692,0.679670
房地产业,0.577236,0.554688,0.698413,0.725806,0.715447,0.625954,0.728000,0.761905,0.720000,0.678605
租赁和商务服务业,0.558824,0.648649,0.638889,0.710526,0.650000,0.714286,0.833333,0.740741,0.571429,0.674075
批发和零售业,0.583942,0.565517,0.668919,0.696552,0.680272,0.657895,0.748466,0.767857,0.678571,0.671999
电力、热力、燃气及水生产和供应业,0.549451,0.586957,0.632653,0.729167,0.683673,0.669903,0.762376,0.706422,0.711712,0.670257
采矿业,0.619048,0.735294,0.731343,0.782609,0.652174,0.430556,0.552632,0.684211,0.607595,0.643940
卫生和社会工作,0.666667,0.600000,0.636364,0.500000,0.307692,0.500000,0.500000,0.750000,0.583333,0.560451
住宿和餐饮业,0.500000,0.500000,0.800000,0.636364,0.400000,0.600000,0.400000,0.555556,0.555556,0.549719
农、林、牧、渔业,0.500000,0.676471,0.500000,0.500000,0.500000,0.571429,0.585366,0.512195,0.511628,0.539676
教育,0.333333,0.428571,0.571429,0.571429,0.571429,0.500000,0.625000,0.555556,0.545455,0.522467
综合,0.363636,0.428571,0.545455,0.454545,0.545455,0.571429,0.523810,0.454545,0.409091,0.477393
居民服务、修理和其他服务业,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.166667

# 各行业股利分配方式（转增、送股、派息、派息并转增、派息并送股等）分析

In [18]:
def fenpeifangshi(data):
    data['股利分配方式'] = ''
    da = data[['证券简称','转增比','派息比税前','送股比','股利分配方式']]
    da = da.fillna(-1)
    n = da.shape[0]
    da.reset_index(drop=True, inplace=True)
    for i in range(n):
        a = da.loc[i]['派息比税前']
        b = da.loc[i]['送股比']
        c = da.loc[i]['转增比']
        if a>0 and b>0 and c>0:
            da.loc[i,'股利分配方式'] = '派息、转增并送股'
        elif a>0 and b>0 and c<0:
            da.loc[i,'股利分配方式'] = '派息并送股'
        elif a>0 and b<0 and c>0:
            da.loc[i,'股利分配方式'] = '派息并转增'
        elif a<0 and b>0 and c>0:
            da.loc[i,'股利分配方式'] = '送股并转增'
        elif a>0 and b<0 and c<0:
            da.loc[i,'股利分配方式'] = '派息'
        elif a<0 and b<0 and c>0:
            da.loc[i,'股利分配方式'] = '转增'
        else:
            da.loc[i,'股利分配方式'] = '送股'
    df = pd.DataFrame(da.groupby('股利分配方式').size(),columns=[data.iloc[520]['财政年度']])
    return df

In [19]:
df = pd.concat([fenpeifangshi(data10),fenpeifangshi(data11),fenpeifangshi(data12),
                fenpeifangshi(data13),fenpeifangshi(data14),fenpeifangshi(data15),
                fenpeifangshi(data16),fenpeifangshi(data17),fenpeifangshi(data18)]
               ,axis = 1)
df

           2010    2011  2012  2013    2014  2015    2016    2017    2018
派息        839.0  1139.0  1474  1495  1465.0  1538  2041.0  2278.0  2247.0
派息、转增并送股   71.0    33.0    27    37    58.0    69    26.0    14.0    11.0
派息并转增     377.0   439.0   350   350   430.0   440   410.0   547.0   399.0
派息并送股      70.0    45.0    33    34    39.0    27    31.0    26.0    33.0
转增         95.0    82.0    57    61    95.0   195    84.0    67.0    50.0
送股          1.0     NaN     2     2     2.0     1     NaN     NaN     NaN
送股并转增       NaN     NaN     1     1     NaN     4     1.0     NaN     NaN

# 股利连续分配情况（1年、2年、3年、4年、5年）

In [20]:
def continusFind(num_list):
    s=1
    find_list=[]
    have_list=[]
    while s<=len(num_list)-1:
        if num_list[s]-num_list[s-1]==1:
            flag=s-1
            while (s <= (len(num_list)-1)) and (num_list[s]-num_list[s-1]==1):
                s+=1
            find_list.append(num_list[flag:s])
            have_list+=num_list[flag:s]
        else:
            s+=1
    return find_list

def fenpei(d):
    dataa = d[['证券简称','财政年度']]
    c = dataa.drop_duplicates(['证券简称','财政年度'])
    c.index  = c['财政年度']
    groups = c.groupby('证券简称').groups
    lianxvguli = dict.fromkeys(list(groups.keys()),0)

    for i in range(len(groups)):
        num_list = list(groups[list(groups.keys())[i]].values)
        find_list = continusFind(num_list)
        if len(find_list)==0:
            lianxvguli[list(c.groupby('证券简称').groups.keys())[i]] =1
        else:
            lianxvguli[list(c.groupby('证券简称').groups.keys())[i]]= len(find_list[0])
    return lianxvguli

In [21]:
df = pd.DataFrame(pd.Series(fenpei(data2)))
df = df.reset_index()
df.columns= ['证券简称','连续分配年数']

df2 = data2[['证券简称','一级行业名称']]
df2 = df2.drop_duplicates(['证券简称'])

df3 = df.merge(df2,how = 'left')

In [30]:
df3

        证券简称  连续分配年数            一级行业名称
0     *ST 东力       1               制造业
1     *ST 东碳       1               制造业
2     *ST 中基       1               制造业
3     *ST 中达       1               制造业
4     *ST 云维       1               制造业
5     *ST 凡谷       1               制造业
6     *ST 合泰       1               制造业
7     *ST 国兴       1              房地产业
8     *ST 国商       1          租赁和商务服务业
9     *ST 大有       1               采矿业
10    *ST 大荒       1          农、林、牧、渔业
11    *ST 天化       1               制造业
12    *ST 宇顺       1               制造业
13    *ST 宏盛       1              房地产业
14    *ST 川化       1  电力、热力、燃气及水生产和供应业
15    *ST 工新       1    信息传输、计算机服务和软件业
16    *ST 常林       1            批发和零售业
17    *ST 平能       1               采矿业
18    *ST 康达       1               制造业
19    *ST 慧业       1               制造业
20    *ST 抚钢       1               制造业
21    *ST 新亿       1               制造业
22    *ST 新都       1            住宿和餐饮业
23    *ST 方向       1            批发和零售业
24    *ST 松辽       1         文化、体育和娱乐业
25    *ST 柳化       1               制造业
26    *ST 水井       1               制造业
27    *ST 沧大       1               制造业
28    *ST 盛工       1            批发和零售业
29    *ST 石岘       1          租赁和商务服务业
...      ...     ...               ...
3959    鼎汉技术       8               制造业
3960    鼎泰新材       6       交通运输、仓储和邮政业
3961    鼎立股份       4               制造业
3962    鼎胜新材       2               制造业
3963    鼎龙股份       9               制造业
3964    齐峰新材       6               制造业
3965    齐峰股份       3               制造业
3966    齐心文具       3               制造业
3967    齐心集团       3               制造业
3968    齐星铁塔       1    信息传输、计算机服务和软件业
3969    齐翔腾达       9               制造业
3970    龙元建设       9               建筑业
3971    龙净环保       9               制造业
3972    龙力生物       4               制造业
3973    龙大肉食       5               制造业
3974    龙头股份       2               制造业
3975    龙宇燃油       2            批发和零售业
3976    龙建股份       9               建筑业
3977    龙星化工       2               制造业
3978    龙江交通       9       交通运输、仓储和邮政业
3979    龙泉股份       6               制造业
3980    龙津药业       4               制造业
3981    龙洲股份       7       交通运输、仓储和邮政业
3982    龙源技术       5               制造业
3983    龙溪股份       9               制造业
3984    龙生股份       5               制造业
3985    龙蟒佰利       3               制造业
3986    龙蟠科技       2               制造业
3987    龙韵股份       4          租赁和商务服务业
3988    龙马环卫       5               制造业

[3989 rows x 3 columns]

In [56]:
def niandulianxv(i,df):
    df = df[df['连续分配年数']==i]
    fenbu = df['一级行业名称'].value_counts()
    return fenbu

In [57]:
df4 = pd.concat([pd.DataFrame(niandulianxv(1,df3)),pd.DataFrame(niandulianxv(2,df3)),pd.DataFrame(niandulianxv(3,df3)),
                pd.DataFrame(niandulianxv(4,df3)),pd.DataFrame(niandulianxv(5,df3)),pd.DataFrame(niandulianxv(6,df3)),
                pd.DataFrame(niandulianxv(7,df3)),pd.DataFrame(niandulianxv(8,df3)),pd.DataFrame(niandulianxv(9,df3))],
               join='outer', axis=1)
df4.columns = [i for i in range(1,10)]

In [58]:
df4 = df4.fillna(0)

In [59]:
df4['总计'] = df4.sum(1)

In [60]:
df4

,1,2,3,4,5,6,7,8,9,总计
交通运输、仓储和邮政业,13,15.0,15.0,4.0,2.0,6.0,8.0,7.0,41.0,111.0
住宿和餐饮业,1,4.0,2.0,0.0,0.0,1.0,1.0,0.0,2.0,11.0
信息传输、计算机服务和软件业,41,64.0,69.0,35.0,20.0,24.0,20.0,23.0,26.0,322.0
农、林、牧、渔业,8,9.0,5.0,7.0,5.0,2.0,4.0,1.0,1.0,42.0
制造业,321,539.0,382.0,249.0,216.0,127.0,126.0,167.0,314.0,2441.0
卫生和社会工作,5,3.0,4.0,2.0,1.0,0.0,0.0,1.0,1.0,17.0
居民服务、修理和其他服务业,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
建筑业,15,18.0,20.0,9.0,3.0,9.0,5.0,5.0,23.0,107.0
房地产业,26,18.0,16.0,14.0,11.0,8.0,9.0,11.0,30.0,143.0
批发和零售业,30,37.0,25.0,23.0,9.0,7.0,12.0,12.0,34.0,189.0
教育,2,5.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,11.0
文化、体育和娱乐业,8,17.0,12.0,9.0,3.0,3.0,4.0,6.0,6.0,68.0
水利、环境和公共设施管理业,9,12.0,13.0,12.0,7.0,2.0,0.0,4.0,6.0,65.0
电力、热力、燃气及水生产和供应业,18,16.0,13.0,11.0,11.0,6.0,10.0,5.0,26.0,116.0
科学研究和技术服务业,11,17.0,9.0,4.0,6.0,1.0,0.0,3.0,4.0,55.0
租赁和商务服务业,11,15.0,7.0,8.0,0.0,5.0,5.0,4.0,6.0,61.0
综合,5,7.0,1.0,2.0,0.0,1.0,5.0,1.0,0.0,22.0
采矿业,17,15.0,12.0,9.0,9.0,2.0,3.0,6.0,12.0,85.0
金融业,25,18.0,19.0,10.0,8.0,3.0,5.0,7.0,26.0,121.0

In [61]:
df4[1]/df4['总计']+(df4[2]/df4['总计'])*2+(df4[3]/df4['总计'])*3+(df4[4]/df4['总计'])*4+(df4[5]/df4['总计'])*5+(df4[6]/df4['总计'])*6+(df4[7]/df4['总计'])*7+(df4[8]/df4['总计'])*8+(df4[9]/df4['总计'])*9

交通运输、仓储和邮政业         5.684685
住宿和餐饮业              4.181818
信息传输、计算机服务和软件业      4.093168
农、林、牧、渔业            3.595238
制造业                 4.271610
卫生和社会工作             3.117647
居民服务、修理和其他服务业       1.000000
建筑业                 4.654206
房地产业                4.825175
批发和零售业              4.465608
教育                  2.636364
文化、体育和娱乐业           4.073529
水利、环境和公共设施管理业       3.892308
电力、热力、燃气及水生产和供应业    4.896552
科学研究和技术服务业          3.345455
租赁和商务服务业            4.016393
综合                  3.590909
采矿业                 4.152941
金融业                 4.471074
dtype: float64

In [62]:
df4['平均连续年数'] = df4[1]/df4['总计']+(df4[2]/df4['总计'])*2+(df4[3]/df4['总计'])*3+(df4[4]/df4['总计'])*4+(df4[5]/df4['总计'])*5+(df4[6]/df4['总计'])*6+(df4[7]/df4['总计'])*7+(df4[8]/df4['总计'])*8+(df4[9]/df4['总计'])*9

In [63]:
df4

,1,2,3,4,5,6,7,8,9,总计,平均连续年数
交通运输、仓储和邮政业,13,15.0,15.0,4.0,2.0,6.0,8.0,7.0,41.0,111.0,5.684685
住宿和餐饮业,1,4.0,2.0,0.0,0.0,1.0,1.0,0.0,2.0,11.0,4.181818
信息传输、计算机服务和软件业,41,64.0,69.0,35.0,20.0,24.0,20.0,23.0,26.0,322.0,4.093168
农、林、牧、渔业,8,9.0,5.0,7.0,5.0,2.0,4.0,1.0,1.0,42.0,3.595238
制造业,321,539.0,382.0,249.0,216.0,127.0,126.0,167.0,314.0,2441.0,4.271610
卫生和社会工作,5,3.0,4.0,2.0,1.0,0.0,0.0,1.0,1.0,17.0,3.117647
居民服务、修理和其他服务业,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.000000
建筑业,15,18.0,20.0,9.0,3.0,9.0,5.0,5.0,23.0,107.0,4.654206
房地产业,26,18.0,16.0,14.0,11.0,8.0,9.0,11.0,30.0,143.0,4.825175
批发和零售业,30,37.0,25.0,23.0,9.0,7.0,12.0,12.0,34.0,189.0,4.465608
教育,2,5.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,11.0,2.636364
文化、体育和娱乐业,8,17.0,12.0,9.0,3.0,3.0,4.0,6.0,6.0,68.0,4.073529
水利、环境和公共设施管理业,9,12.0,13.0,12.0,7.0,2.0,0.0,4.0,6.0,65.0,3.892308
电力、热力、燃气及水生产和供应业,18,16.0,13.0,11.0,11.0,6.0,10.0,5.0,26.0,116.0,4.896552
科学研究和技术服务业,11,17.0,9.0,4.0,6.0,1.0,0.0,3.0,4.0,55.0,3.345455
租赁和商务服务业,11,15.0,7.0,8.0,0.0,5.0,5.0,4.0,6.0,61.0,4.016393
综合,5,7.0,1.0,2.0,0.0,1.0,5.0,1.0,0.0,22.0,3.590909
采矿业,17,15.0,12.0,9.0,9.0,2.0,3.0,6.0,12.0,85.0,4.152941
金融业,25,18.0,19.0,10.0,8.0,3.0,5.0,7.0,26.0,121.0,4.471074

In [64]:
df4 = df4.sort_values(by='平均连续年数',ascending=False)
df4

,1,2,3,4,5,6,7,8,9,总计,平均连续年数
交通运输、仓储和邮政业,13,15.0,15.0,4.0,2.0,6.0,8.0,7.0,41.0,111.0,5.684685
电力、热力、燃气及水生产和供应业,18,16.0,13.0,11.0,11.0,6.0,10.0,5.0,26.0,116.0,4.896552
房地产业,26,18.0,16.0,14.0,11.0,8.0,9.0,11.0,30.0,143.0,4.825175
建筑业,15,18.0,20.0,9.0,3.0,9.0,5.0,5.0,23.0,107.0,4.654206
金融业,25,18.0,19.0,10.0,8.0,3.0,5.0,7.0,26.0,121.0,4.471074
批发和零售业,30,37.0,25.0,23.0,9.0,7.0,12.0,12.0,34.0,189.0,4.465608
制造业,321,539.0,382.0,249.0,216.0,127.0,126.0,167.0,314.0,2441.0,4.271610
住宿和餐饮业,1,4.0,2.0,0.0,0.0,1.0,1.0,0.0,2.0,11.0,4.181818
采矿业,17,15.0,12.0,9.0,9.0,2.0,3.0,6.0,12.0,85.0,4.152941
信息传输、计算机服务和软件业,41,64.0,69.0,35.0,20.0,24.0,20.0,23.0,26.0,322.0,4.093168
文化、体育和娱乐业,8,17.0,12.0,9.0,3.0,3.0,4.0,6.0,6.0,68.0,4.073529
租赁和商务服务业,11,15.0,7.0,8.0,0.0,5.0,5.0,4.0,6.0,61.0,4.016393
水利、环境和公共设施管理业,9,12.0,13.0,12.0,7.0,2.0,0.0,4.0,6.0,65.0,3.892308
农、林、牧、渔业,8,9.0,5.0,7.0,5.0,2.0,4.0,1.0,1.0,42.0,3.595238
综合,5,7.0,1.0,2.0,0.0,1.0,5.0,1.0,0.0,22.0,3.590909
科学研究和技术服务业,11,17.0,9.0,4.0,6.0,1.0,0.0,3.0,4.0,55.0,3.345455
卫生和社会工作,5,3.0,4.0,2.0,1.0,0.0,0.0,1.0,1.0,17.0,3.117647
教育,2,5.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,11.0,2.636364
居民服务、修理和其他服务业,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.000000